markdown: kramdown
highlighter: rouge

permalink: /blog/:year/:month/:day/:title/

# Setup
mywebsite:
  url: http://jojozhuang.github.io
  copyright: '&copy; 2017 jojozhuang.github.io, All rights reserved.'
#theme: jekyll-theme-cayman

author:
  name: 'Rong Zhuang'
  email: 'jojozhuang@gmail.com'
  phone: '(+1) 650 380 4437'
  linkedin: https://www.linkedin.com/in/rongzhuang

navlist:
  - key: portfolio
    url: /portfolio
    visible: true
  - key: blog
    url: /blog
    visible: true
  - key: cv
    url: /cv
    visible: false
  - key: course
    url: /course
    visible: false
  - key: favorite
    url: /favorite
    visible: true
  - key: feed
    url: /blog/atom.xml"
    visible: false
  - key: more
    url: /#
    visible: true
    subkeys: library,note
    sublist:
      - key: library
        url: /library
      - key: note
        url: /note
  - key: about
    url: /about
    visible: true

collections:
  portfolio:
    output: true
  note:
    output: true
#https://sacha.me/articles/jekyll-rouge/
#https://github.com/ZhengshuaiPENG/zhengshuaipeng.github.io/blob/master/_config.yml
